dataset: cifar100
num_classes: 100
img_size: 32
mean:
    - 0.5071
    - 0.4867
    - 0.4408
std:
    - 0.2675
    - 0.2565
    - 0.2761
crop_pct: 1.0
scale:
    - 0.8
    - 1.0
interpolation: bicubic
train_interpolation: random
aa: rand-m9-mstd0.5-inc1
mixup: 0.8
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_mode: batch
mixup_switch_prob: 0.5
cutmix: 1.0
reprob: 0.25
remode: pixel
amp: True
model: cct_7_3x1_32_sine
model_ema: False
batch_size: 128
lr: 7e-4
min_lr: 1e-5
sched: cosine
weight_decay: 5e-2
epochs: 1500
cooldown_epochs: 10
warmup_epochs: 10
warmup_lr: 0.000001
opt: adamw
smoothing: 0.1
workers: 8