dataset: imagenet
num_classes: 1000
img_size: 224
mean:
    - 0.485
    - 0.456
    - 0.406
std:
    - 0.229
    - 0.224
    - 0.225
crop_pct: 0.9
scale:
    - 0.08
    - 1.0
interpolation: bicubic
train_interpolation: random
aa: rand-m9-mstd0.5-inc1
mixup: 0.8
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_mode: batch
mixup_switch_prob: 0.5
cutmix: 1.0
reprob: 0.25
remode: pixel
amp: True
batch_size: 128
lr: 5e-4
min_lr: 0.00001
sched: cosine
weight_decay: 5e-2
epochs: 300
cooldown_epochs: 10
warmup_epochs: 25
warmup_lr: 0.000001
opt: adamw
smoothing: 0.1
workers: 8